spring:
  application:
    name: springai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:8b
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.pain.springai: debug